enum:

  unidom_calculation:
    amount:
      code: AMNT
    percentage:
      code: PCTG

  unidom_charging:
    one_time:
      code:        ONCE
      description: such as for buying a good
    recurring:
      code:        RECR
      description: an ongoing charge such as a monthly fee for a standard type of service
    utilization:
      code:        UTLZ
      description: usage of a product

  unidom_pricing:
    base:
      code: BASE
      description: 产品的起始价格
    discount:
      code: DSCT
      description: 相对于基价的有效折扣
    surcharge:
      code: SCHG
      description: 附加收费
    manufacturer_suggested:
      code: MFSG
      description:
